### ISSUE TITLE
load the svg image from network

### ISSUE THREAD

**Issue by xoxoj** [excellentingenuity/laravel-mix-vue-svgicon#3]
ex. if I want load the svg image from url, as https://xxx.xxx.com/file/some.svg, how can I do.

thanks.

**Comment by excellentingenuity** [comment]
I am sorry but the way this plugin is designed to work with Laravel mix, which is a command line tool for local asset compilation, getting an svg from a url will not work. However, if you before calling this plugin called one of your own that fetched the svg's and placed them in a directory locally it could be done that way.
