### ISSUE TITLE
Relative path not correct, Can't resolve 'SVGPATH'

### ISSUE THREAD

**Issue by packytagliaferro** [excellentingenuity/laravel-mix-vue-svgicon#4]
In the docs you say that the default path is `./../public/resources/svg` to work with Adam Wathan's Blade SVG package. His package, which I have and works, uses the path `resources/svg`. If I have mix in the root directory the this should be the correct location since the default doesn't work:

```
const mix = require('laravel-mix');
require('laravel-mix-tailwind');
require('laravel-mix-purgecss');
require('laravel-mix-vue-svgicon');

mix.js('resources/js/erro.js', 'public/js')
    .sass('resources/sass/erro.scss', 'public/css')
    .tailwind('tailwind.config.js')
    .version()
    .svgicon('resources/svg/logo.svg')
    .purgeCss();
```

But I get the error `Error: Can't resolve 'SVGPATH'`. 

I have also tried:

` .svgicon('./resources/svg/logo.svg')`

So not sure why its not working and if you want to be inline with Adam Wathan's package the default should point to `/resources/svg/`, not the public directory.

**Comment by excellentingenuity** [comment]
Thanks for posting this issue. You are welcome to submit a pull request that updates the default path with the updated path from Adam Wathan's package.
